[profile.default]
src = 'src'
test = 'test'
no_match_contract = "OptionSettlementTest"
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/', 
    'solmate/=lib/solmate/src/', 
    'valorem-core/=lib/valorem-core/',
    'ds-test/=lib/ds-test/src/'
]